on:
 push:
   branches: [ "master" ]
 pull_request:
   branches: [ "master" ]

jobs:
 build:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       node-version: [20.x]
   steps:
   - uses: actions/checkout@v4
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v4
     with:
       node-version: ${{ matrix.node-version }}
       cache: 'npm'
   - run: npm ci
   - run: npm run build --if-present
   - run: npm test

#  sonar:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0

#      - name: Set up Node
#        uses: actions/setup-node@v4
#        with:
#          node-version: '20.x'
#          cache: 'npm'

#      - name: Install dependencies
#        run: npm ci

#      - name: Build project
#        run: npm run build

#      - name: SonarCloud Scan
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        with:
#          args: >
#            -Dsonar.ci=true
#            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
#            -Dsonar.pullrequest.branch=${{ github.head_ref }}
#            -Dsonar.pullrequest.base=${{ github.base_ref }}